  # fly.toml app configuration file generated for quizzes on 2023-07-21T15:12:04+02:00
  #
  # See https://fly.io/docs/reference/configuration/ for information about how to use this file.
  #

  app = "quizzes"
  primary_region = "arn"

  [http_service]
    internal_port = 7777
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    processes = ["app"]
